### ISSUE TITLE
Error in correlation part

### ISSUE THREAD

**Issue by hust-yyan** [Xinglab/PEGASAS#2]
Hello, when I ran the second part of the Correlation, I encountered the following error message：
![image](https://user-images.githubusercontent.com/54279739/109750247-0d0d4e80-7c17-11eb-82d7-e74701364816.png)
this is my code:
export PATH=~/.conda/envs/yyan2.7/bin/:$PATH
outdir=/data1/yyan_tmp/LUNG_CANCER/analysis/rmats_output/PEGASAS_output
groupNameOrder=/data1/yyan_tmp/LUNG_CANCER/analysis/rmats_output/PEGASAS_output/groupOrder.txt
PEGASAS correlation \
 $outdir/SCORE/SCORE.scores.txt  \
 /data1/yyan_tmp/LUNG_CANCER/analysis/rmats_output/TYPE.JC.filter.PSI.txt $groupNameOrder \
-o $outdir --GO  
And the *.JC.filter.PSI.txt is as follow:
![image](https://user-images.githubusercontent.com/54279739/109750388-51005380-7c17-11eb-9441-e682c9b299ae.png)
Could you help me see how to solve this problem

**Comment by ypnngaa-py** [comment]
Hi, 
This seems to be a format issue. As the toy example provided in the Readme, the format of the should explicitly contain gene AC/name and splicing event coordinates (details see the example file): https://raw.githubusercontent.com/Xinglab/PEGASAS/master/example/PSIbySample_example.txt

Yang

**Comment by hust-yyan** [comment]
Thank you very much. The problem has been solved.
I want to ask why the first column AC in https://raw.githubusercontent.com/Xinglab/PEGASAS/master/example/PSIbySample_example.txt is in {gene_id}_{number} form, and what does number mean.

**Comment by ypnngaa-py** [comment]
I believe the AC format comes from the Gencode GTF annotation. This is just an example to show the format and required columns, you may use any annotation you prefer. You may even fill up these columns with any values/names as long as you can distinguish the splicing event. The only thing matters here is the header names - it requires to have 'AC' 'chr' .. etc to be recognized.  
Let me know if you have any questions. Thanks!

**Comment by hust-yyan** [comment]
I have another question, do the columns "corrected_score" and "adjusted_corrected_score" in the GO_result_table_hallmarks_SIGNALING.txt file refer to the P value of the hypergeometric distribution test

**Comment by ypnngaa-py** [comment]
Right. The corrected score is based on a hypergeometric test using a
customized background list to account for high expression genes. The
adjusted corrected score is simply the score after the Benjamini-Hochberg
procedure to control  FDR at 5%.
For detailed description, see supplementary method in the paper
https://www.pnas.org/content/pnas/suppl/2020/02/20/1915975117.DCSupplemental/pnas.1915975117.sapp.pdf

**Comment by hust-yyan** [comment]
Hello, may I ask what each column in this output HALLMARK_XENOBIOTIC_METABOLISM.scores.txt refers to

**Comment by ypnngaa-py** [comment]
Sorry I just saw this.
for the 'scores.txt' file from the pathway step, the column names are:
sample ID, group ID, K-S statistic, K-S pvalue. 
This is a intermediate file, so please ignore the p-value. Only the statistic is being used as scores for the correlation analysis. The permutation based p value is calculated in the later step.

**Comment by hust-yyan** [comment]
I just saw it today. Thank you very much. The problem has been solved.



At 2021-03-14 06:44:04, "ypnngaa-py" ***@***.***> wrote:

Sorry I just saw this.
for the 'scores.txt' file from the pathway step, the column names are:
sample ID, group ID, K-S statistic, K-S pvalue.
This is a intermediate file, so please ignore the p-value. Only the statistic is being used as scores for the correlation analysis. The permutation based p value is calculated in the later step.
