### ISSUE TITLE
How to map high correlated events to groups

### ISSUE THREAD

**Issue by komalsrathi** [Xinglab/PEGASAS#5]
I have the final output for each correlation run which is a `*high_cor_matrix.txt` file with splice events + correlation value + p-value for a specific pathway. 

But there is no sample level or group level associations in the output. How should we map the info given by PEGASAS to the groups of interest? How and where is the information within `groupNameOrder.txt` being used in the `correlation` command? 

Example of splice events in the output file for `KEGG_ABC_TRANSPORTERS`, filtered to `absolute cor_keep > 0.7`:

```
  correlated                                            cor_keep p_keep pathway              
  <chr>                                                    <dbl>  <dbl> <chr>                
1 ADCYAP1R1_chr7_+_31103237_31103366_31092735_31106495     0.892      0 KEGG_ABC_TRANSPORTERS
2 COP1_chr1_-_176184633_176184692_176176007_176206571     -0.729      0 KEGG_ABC_TRANSPORTERS
3 TET2_chr4_+_105233897_105237351_105146979_105259618      0.980      0 KEGG_ABC_TRANSPORTERS
4 WDR44_chrX_+_118442244_118442345_118436824_118442564     0.930      0 KEGG_ABC_TRANSPORTERS
5 CARS2_chr13_-_110701438_110701555_110688018_110713136   -0.875      0 KEGG_ABC_TRANSPORTERS
6 NET1_chr10_+_5453250_5453346_5452920_5453483            -0.725      0 KEGG_ABC_TRANSPORTERS 
```

Thanks,
Komal

**Comment by ypnngaa-py** [comment]
Hi, Komal. My apologies for the delayed response; I somehow missed the GitHub notification during my international travel. 
Regarding your question :
> "But there is no sample level or group level associations in the output. How should we map the info given by PEGASAS to the groups of interest? "

I'd like to clarify that the correlation between a given AS event and a pathway is calculated using each individual sample's value as data points. Therefore, it is expected not to have sample-level estimation. Concerning 'group-level,' if you have pre-defined groups and you want to understand the relationship between AS events and pathways for each group separately, please input one group at a time and run PEGASAS separately. We do not support automatic splitting of the input by 'groupNameOrder.'

> How and where is the information within groupNameOrder.txt being used in the correlation command?  

and from your email

> Why does the correlation command even use the groupNameOrder.txt file if the output does not reflect group-specific enrichments?

As described in the README of this option, "...The group name should match the group info list in the pathway score calculation step. This is useful for the heatmap visualization." This information helps to generate the heatmap with group names,  such as Fig 3A in the paper.

I hope this addresses your questions. Please feel free to reach out if you have any further inquiries.

**Comment by ypnngaa-py** [comment]
Continue my above response, just wanted to add two examples that may be relevant to your analysis: 
1. Figure 3B shows the correlation between AS and pathway, showing why there won't be a sample-level correlation, you can see each point in the scatterplot represents one sample with y axis being AS PSI value and x axis being the pathway score.
 2. For group-level visualization, you can try Fig 3C, a sashimi plot, which is available at Xing lab GitHub repo at : https://github.com/Xinglab/rmats2sashimiplot  Again, this doesn't not show group-level correlation but a visualization. For group-level correlation, you can try what I described in my last response.
Hope this helps.

Sincerely,
Yang

**Comment by komalsrathi** [comment]
Hi @ypnngaa-py thank you for your responses. Makes sense now. I was having trouble with mapping the "highly correlated" splice events to pathways and to my groups of interest. 

I'll give you a brief context of my analysis and if possible would like to know what your thoughts are on my approach:

We have 14 clusters identified from 152 samples from a multi-modal clustering approach. My goal is to identify splice events that are contributing/specific to each of the clusters. I have previously run the PEGASAS `pathway` command using the full KEGG database. Based on your response, my approach is to do the following for each of the 14 clusters of interest:

1. DESeq2 to perform differential expression on the `gene expression matrix` using `cluster_of_interest vs rest` approach i.e. cluster 1 vs all other clusters, cluster 2 vs all other clusters and so on. 

2. Pre-ranked enrichment using `fgsea` on differentially expressed genes identified from 1)

3. Run PEGASAS `correlation` command using only differentially regulated pathways from step 2, in order to reduce runtimes and to get splice events specific to pathways enriched in cluster of interest. I guess my question for this step is: the output files are completely independent of the cluster information, correct? I am asking this because I have already run the `correlation` command on the full splice matrix of 152 samples along with the clustering annotation. So I think I don't need to run this again as the results won't change, right? For each cluster, I only need to pull the `highly correlated events output` for the pathways for which there is an enrichment seen in that cluster? 

OR

3. For this step, should I subset the PSI matrix to samples from the cluster of interest only and rerun the `correlation` command on the pathways of interest? For example, I have 2 pathways enriched for cluster 1 vs other clusters from gene expression, I would first subset the PSI matrix to samples in cluster 1 and run the `correlation` command on this subset matrix and the two enriched pathways only.

**Comment by ypnngaa-py** [comment]
I personally think that the 'first' step 3 is a better approach. You already have pathway enrichment derived from the cluster of interest, and you want to identify AS events associated with it. I think running it against the full dataset of 152 samples is a good approach and can help identify AS events associated with the pathway. As for the second option, it may also work, but you will have a much smaller sample size (only one of 14 clusters from 152 samples), so I am uncertain about how well the correlation could perform.
Stepping back, assuming both strategies work effectively, they may answer slightly different questions. One seems to identify pathway-associated AS events in all samples, while the other seems to find AS events in a specific cluster or subtype.  
This is just my opinion and may not suit your analysis, so take what you want.

**Comment by komalsrathi** [comment]
@ypnngaa-py Ok thank you, closing this.
